version: "3.4"
services:
  wordpress:
    image: wordpress:v1
    container_name: wordpress
    hostname: wordpress
    networks:
      wordpress_net:
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    volumes:
      - ${PWD}/data:/var/lib/mysql
    networks:
      wordpress_net:
    environment:
      - MYSQL_ROOT_PASSWORD=12345

networks:
  wordpress_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
