FROM ubuntu:18.04
RUN apt update -y && apt install gpg -y && \
    apt -y install software-properties-common && \
    yes "" | add-apt-repository ppa:ondrej/php && \
    apt-get update -y && echo Asia/Shanghai > /etc/timezone && \
    ln -snf  /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
    apt -y install php7.4 php7.4-mysql nginx php7.4-fpm php7.4-xml nginx monit

ADD ./config/ /
RUN chmod +x /usr/sbin/run_monit.sh
ENTRYPOINT [ "/usr/sbin/run_monit.sh" ]
